/**
 * Bundle the AIRLOCK MCP server into one self-contained file.
 *
 * The server runs as a child process of whatever mounts it, and that process
 * does not necessarily live where this repository does. Two cases made the
 * bundle necessary rather than nice:
 *
 *   - TrueForge in Docker. The repository is bind-mounted into the container,
 *     but `node_modules/@airlock/contract` is a workspace symlink — a junction
 *     on Windows — and it does not survive the mount. Every import would
 *     resolve to nothing, the airlock tools would silently not exist, and the
 *     one tool the harness is supposed to hold for a human would be missing.
 *     Silently. That is the worst possible failure for this particular project.
 *
 *   - `npx -y @airlock/mcp`. A published package must carry its own
 *     dependencies; a bundle is the simplest way to be certain it does.
 *
 * Output is `dist/airlock-mcp.bundle.mjs`, which `bin/airlock-mcp.mjs` prefers
 * and falls back from, so a plain `tsc` build still works for development.
 */
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';

const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(here, 'dist', 'airlock-mcp.bundle.mjs');

const result = await build({
  entryPoints: [path.join(here, 'dist', 'index.js')],
  outfile: out,
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'esm',
  // Node built-ins stay external; everything else — including zod, reached
  // through @airlock/contract — is inlined.
  packages: 'bundle',
  legalComments: 'none',
  banner: {
    js: '// AIRLOCK MCP server — generated by packages/mcp/build.mjs. Do not edit.\n',
  },
  metafile: true,
});

const bytes = fs.statSync(out).size;
const inputs = Object.keys(result.metafile.outputs[Object.keys(result.metafile.outputs)[0]].inputs).length;
console.log(`bundled ${inputs} modules into dist/airlock-mcp.bundle.mjs (${(bytes / 1024).toFixed(0)} kB)`);
